# Generated by Django 5.1.1 on 2024-10-26 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
