# Generated by Django 5.1.1 on 2024-12-23 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
